---

- set_fact:
    data:
      depends_on: []

- set_fact:
    data: '{{ data|combine({ item : value[item] }) }}'
  loop: '{{ iay_fields[type].d
     |union(iay_fields.all)
     |union(iay_fields.all_d) }}'
  when: 'item in value'

- name: 'Check whether data.{{ type }}.{{ key }} has at least one field.'
  include_tasks: 'terraform_write.yml'
  vars:
    file: 'data.{{ type }}.{{ key }}'
    terraform:
      data: '{{ { type : { key : data } } }}'
  when: 'data.keys()|length > 1'
