---

- set_fact:
    data: {}

- set_fact:
    data: '{{ data|combine({ item : value[item] }) }}'
  loop: '{{ infrastructure_fields[type].d|union(infrastructure_fields.all) }}'
  when: 'item in value'

- include_tasks: 'terraform_write.yml'
  vars:
    file: 'data.{{ type }}.{{ key }}'
    terraform:
      data: '{{ { type : { key : data } } }}'
