---

- name: 'Gather ec2_instance_facts data.'
  ec2_instance_facts:
    aws_access_key: '{{ i.aws_access_key
                       |default(aws_access_key|default(omit)) }}'
    aws_secret_key: '{{ i.aws_secret_key
                       |default(aws_secret_key|default(omit)) }}'
    ec2_url: '{{ i.ec2_url
            |default(aws_ec2_url|default(omit)) }}'
    filters: '{{ i.filters
        |default(aws_ec2_filters|default(omit)) }}'
    instance_ids: '{{ i.instance_ids
             |default(aws_ec2_instance_ids|default(omit)) }}'
    profile: '{{ i.profile
            |default(aws_profile|default(omit)) }}'
    region: '{{ i.region
           |default(aws_region|default(omit)) }}'
    security_token: '{{ i.security_token
                   |default(aws_security_token|default(omit)) }}'
    validate_certs: '{{ i.validate_certs
                   |default(aws_validate_certs|default(omit)) }}'
  register: 'facts'

- include_tasks: 'import.yml'
  vars:
    fact: 'instances'
    r_id: 'instance_id'
    r_type: 'aws_instance'
