---

- name: 'Gather ec2_instance facts.'
  ec2_instance_facts:
    aws_access_key: '{{ args.aws_access_key|default(omit) }}'
    aws_secret_key: '{{ args.aws_secret_key|default(omit) }}'
    ec2_url: '{{ args.ec2_url|default(omit) }}'
    filters: '{{ args.filters|default(omit) }}'
    instance_ids: '{{ args.instance_ids|default(omit) }}'
    profile: '{{ args.profile|default(omit) }}'
    region: '{{ args.region|default(omit) }}'
    security_token: '{{ args.security_token|default(omit) }}'
    validate_certs: '{{ args.validate_certs|default(omit) }}'
  register: 'infrastructure_ec2_inventory'

- name: 'Show returned facts.'
  debug:
    var: 'infrastructure_ec2_inventory'
