---

- file:
    path: '{{ path }}/{{ type }}_d_{{ item }}.tf'
    state: 'absent'
  loop: '{{ data_items }}'

- shell: 'terraform state rm data.{{ type }}.{{ item }}'
  args:
    chdir: '{{ path }}'
  loop: '{{ data_items }}'
    
