---

- name: 'Initialize resources.'
  set_fact:
    resources: '{{ i.terraform }}'

- include_tasks: 'write_terraform.yml'
  vars:
    data:
      resource: '{{ resources }}'

- include_tasks: 'import_check.yml'
  loop: '{{ resources|dict2items }}'
  loop_control:
    loop_var: 'r'

- include_tasks: 'write_terraform.yml'
  vars:
    data:
      resource: '{{ resources }}'
