---

- block:
    - include_tasks: 'import_resource.yml'
      loop: '{{ r_list }}'
      vars:
        id: '{{ item[r_id] }}'
        count: '[{{ tag|regex_replace(match, replace) }}]'
      when: 'tag|regex_search(match)'
  vars:
    match: '{{ i.match|default("[^0-9]*[0]*") }}'
    replace: '{{ i.replace|default("") }}'
    tag: '{{ r.value.tags[i.tag|default("Name")]|default("") }}'
