---

# Build facts from terraform data, then import.

- set_fact:
    facts: []

- set_fact:
    facts: '{{
      facts|union(
        [
          { "key" : item.key,
            "value" : {
              i.arg: item.value[i.arg],
              r_id: item.value[i.arg]|regex_replace(
                i.match|default("^"),
                i.replace|default("")
              )
            }
          }
        ]
      )
    }}'
  loop: '{{ i.terraform|dict2items }}'
  
- include_tasks: 'import.yml'
  vars:
    r_list: '{{ facts }}'
