---

# Build facts from terraform data, then import.

- set_fact:
    facts: []

- set_fact:
    facts: '{{
      facts|union( [ {
        i.match|default(i.arg): item[i.arg],
        r_id: item[i.arg]|regex_replace(
          i.match|default("^"),
          i.replace|default("")
        )
      } ] )
    }}'
  loop: '{{ i.terraform.values() }}'

- debug:
    var: 'data'
  vars:
    data:
      facts: '{{ facts }}'
      i: '{{ i }}'
      r_id: '{{ r_id }}'
      r_new: '{{ r_new }}'
      r_type: '{{ r_type }}'
  when: 'r_type == "aws_iam_profile"'
  
- include_tasks: 'import.yml'
  vars:
    r_list: '{{ facts }}'
