---

- include_tasks: 'import_resource.yml'
  vars:
    count: ''
    id: '{{ ids[r_arg] }}'

- debug:
    var: 'import_results.stderr'

- name: 'Remove "Force New" fields: {{ r_new|join(", ") }}'
  set_fact:
    resources: '{{
      resources|combine(
        { r.key: dict(
            r_old|zip(
              r_old|map("extract", r.value)|list
            )
          )
        }
      )
    }}'
  vars:
    r_old: '{{ r.value.keys()|difference(r_new) }}'
  when: 'import_results.rc == 0'
