---

# Build facts from terraform data, then import.

- set_fact:
    facts: []

- set_fact:
    facts: '{{
      facts|union( [ {
        i.match|default(i.arg): item[i.arg],
        r_id: item[i.arg]|regex_replace(
          i.match|default("^"),
          i.replace|default("")
        )
      } ] )
    }}'
  loop: '{{ i.terraform.values() }}'
  
- include_tasks: 'import.yml'
  vars:
    r_list: '{{ facts }}'
