---

- name: 'Make temp directory for terraform run.'
  tempfile:
    state: 'directory'
  register: 'infrastructure_tempdir'

- name: 'Inititialize terraform.'
  shell: 'terraform init'
  args:
    chdir: '{{ infrastructure_tempdir.path }}'

- name: 'Include infrastructure_vars.'
  include_vars:
    depth: '{{ item.depth|default(omit) }}'
    dir: '{{ item.dir|default(omit) }}'
    extensions: '{{ item.extensions|default(omit) }}'
    file: '{{ item.file|default(omit) }}'
    files_matching: '{{ item.files_matching|default(omit) }}'
    ignore_files: '{{ item.ignore_files|default(omit) }}'
    ignore_unknown_extensions: '{{ item.ignore_unknown_extensions|default(omit) }}'
    name: '{{ item.name|default(omit) }}'
  loop: '{{ infrastructure_vars|default([]) }}'
  when: 'item is mapping'

- name: 'Loop through infrastructure variable.'
  include_tasks: '{{ i.task }}.yml'
  loop: '{{ infrastructure }}'
  loop_control:
    loop_var: 'i'

- name: 'Build a terraform plan.'
  ignore_errors: true
  loop:
    - 'planned'
    - 'present'
  register: 'terraform'
  terraform:
    plan_file: '{{ infrastructure_tempdir.path }}/tower-build.tfplan'
    project_path: '{{ infrastructure_tempdir.path }}'
    state: '{{ item }}'

- debug:
    msg: '{{ item|regex_replace("\\n","\n")
                 |regex_replace("\\t","\t")
                 |regex_replace("\\\"","\"") }}'
  loop:
    - '{{ terraform.results.0.msg|default("") }}'
    - '{{ terraform.results.0.stdout|default("") }}'
    - '{{ terraform.results.1.msg|default("") }}'
    - '{{ terraform.results.1.stdout|default("") }}'
