---

- name: 'Fetch ec2 metatdata.'
  ec2_metadata_facts:
  when: 'aws_account is not defined'

- set_fact:
    iay_imports: []

- name: 'Make temp directory for terraform run.'
  tempfile:
    path: '{{ path|default(omit, true) }}'
    prefix: '{{ lookup("vars","iay_tempdir.prefix",default="iay.") }}'
    state: 'directory'
    suffix: '{{ lookup("vars","iay_tempdir.suffix",default=".temp") }}'
  register: 'iay_tempdir'
  vars:
    paths: '{{ [lookup("vars","iay_tempdir.path",default="/"),"/"] }}'
    path: '{{ lookup("first_found",paths)|regex_replace("/$","") }}'
    persist: '{{ lookup("vars","iay_tempdir.persist",default=false) }}'
  when: 'path == "" or not persist'

- block:

    - include_tasks: 'providers_add.yml'
      loop: '{{ iay|default({}, true)|dict2items }}'
      loop_control:
        loop_var: 'p'

    - include_tasks: 'terraform_apply.yml'
      vars:
        action: '{{ iay_action }}'

    - name: 'Retrieve final terraform state.'
      shell: 'terraform state pull'
      args:
        chdir: '{{ path }}'
      register: 'iay_state'

    - name: 'Parse json from terraform state.'
      set_fact:
        iay_state: '{{ iay_state.stdout|from_json }}'

    - file:
        path: '{{ path }}'
        state: 'absent'
      when: 'not iay_tempdir.persist|default(false)'

  vars:
    path: '{{ iay_tempdir.path }}'
