---

- name: 'Make temp directory for terraform run.'
  tempfile:
    state: 'directory'
  register: 'infrastructure_tempdir'

- include_tasks: 'providers.yml'
  loop: '{{ infrastructure|dict2items }}'
  loop_control:
    loop_var: 'providers'
  vars:
    path: '{{ infrastructure_tempdir.path }}'
