---

- name: 'Make temp directory for terraform run.'
  tempfile:
    state: 'directory'
  register: 'infrastructure_tempdir'

- include_tasks: 'provider.yml'
  loop: '{{ infrastructure|dict2items }}'
  loop_control:
    loop_var: 'provider'
  vars:
    path: '{{ infrastructure_tempdir.path }}'
