---

- name: 'Initialize imports list.'
  set_fact:
    imports: []

- name: 'Make temp directory for terraform run.'
  changed_when: false
  tempfile:
    state: 'directory'
  register: 'iay_tempdir'

- block:

    - include_tasks: 'providers_add.yml'
      loop: '{{ iay|dict2items }}'
      loop_control:
        loop_var: 'p'

    - include_tasks: 'terraform_apply.yml'
      vars:
        state: '{{ iay_state }}'

    - file:
        path: '{{ path }}'
        state: 'absent'
      changed_when: false

  vars:
    path: '{{ iay_tempdir.path }}'
