---

- include_tasks: 'write_provider.yml'
  vars:
    key: '{{ providers.key }}'
    value: '{{ providers.value }}'

- include_tasks: '{{ backends.key }}_backend.yml'
  loop: '{{ providers.value.backend|default({})|dict2items }}'
  loop_control:
    loop_var: 'backends'
  vars:
    backend:
      head: '{{ backends.value|dirname }}'
      full: '{{ backends.value }}'
      tail: '{{ backends.value|regex_replace("^"+(backends.value|dirname)+"/","") }}'
    provider: '{{ providers.key }}'

- include_tasks: 'data_items.yml'
  loop: '{{ providers.value.data|dict2items }}'
  loop_control:
    loop_var: 'datas'
  vars:
    data_items: '{{ datas.value }}'
    provider: '{{ providers.key }}'
    type: '{{ providers.key }}_{{ datas.key }}'
      
- include_tasks: 'resource_list.yml'
  loop: '{{ providers.value.resource|default([]) }}'
  loop_control:
    loop_var: 'resource_list'
  vars:
    provider: '{{ providers.key }}'
