---

- include_tasks: 'write_terraform.yml'
  vars:
    file: 'provider_{{ providers.key }}'
    terraform:
      provider: '{{
        { providers.key : providers.value.args }
      }}'

- name: 'Load terraform plugins.'
  args:
    chdir: '{{ infrastructure_tempdir.path }}'
  shell: 'terraform init'

- include_tasks: 'data_list.yml'
  loop: '{{ providers.value.data|default([]) }}'
  loop_control:
    loop_var: 'data_list'
  vars:
    provider: '{{ providers.key }}'
      
- include_tasks: 'resource_list.yml'
  loop: '{{ providers.value.resource|default([]) }}'
  loop_control:
    loop_var: 'resource_list'
  vars:
    provider: '{{ providers.key }}'
