---

- include_tasks: 'write_terraform.yml'
  vars:
    data:
      provider: '{{ i.terraform }}'

- name: 'Load terraform plugins.'
  args:
    chdir: '{{ infrastructure_tempdir.path }}'
  shell: 'terraform init'
