---

- name: 'Write the {{ i.file }}.tf file.'
  copy:
    content: '{{ yaml|to_nice_json }}'
    dest: '{{ infrastructure_tempdir.path }}/{{ i.file }}.tf'
  vars:
    yaml:
      provider: '{{ i.terraform }}'

- name: 'Load terraform plugins.'
  args:
    chdir: '{{ infrastructure_tempdir.path }}'
  shell: 'terraform init'
