---

- set_fact:
    provider: {}

- set_fact:
    provider: '{{ provider|combine({ item : value[item] }) }}'
  loop: '{{ infrastructure_fields[key].p }}'
  when: 'item in value'

- include_tasks: 'terraform_write.yml'
  vars:
    file: '{{ key }}_p'
    terraform:
      provider: '{{ { key : provider } }}'
