---


- name: 'Check whether {{ type }} is importable.'
  include_tasks: 'resource_import.yml'
  when: '"+i" in iay_fields[type]'

- name: 'Initialize resource.'
  set_fact:
    resource: {}

- name: 'Loop through allowed fields to build resource.'
  set_fact:
    resource: '{{ resource|combine({ item : value[item] }) }}'
  loop: '{{ iay_fields[type].r
     |union(iay_fields.all)
     |union(iay_fields.all_r) }}'
  when: 'item in value'

- include_tasks: 'terraform_write.yml'
  vars:
    file: '{{ type }}.{{ key }}'
    terraform:
      resource: '{{ { type : { key : resource } } }}'
