---

- name: 'Initialize import id.'
  set_fact:
    id: '{{ iay_fields[type]["+i"]|default(none) }}'

- name: 'Loop through value fields to interpolate import id.'
  set_fact:
    id: '{{ id|regex_replace(srch,repl) }}'
  loop: '{{ value|dict2items }}'
  vars:
    srch: '\+{{ item.key }}(?![A-Za-z_])'
    repl: '{{ item.value|string|to_json }}'

- name: 'Finish interpolating import id for data.'
  set_fact:
    id: '{{ id|regex_replace(srch, repl) }}'
  vars:
    srch: '\+'
    repl: 'data.{{ type }}.{{ key }}.'
  when: '"d" in iay_fields[type]'

- name: 'Finish interpolating import id for no data.'
  set_fact:
    id: '{{ id|regex_replace(srch, repl) }}'
  vars:
    srch: '\+[A-Za-z_]+'
    repl: '""'
  when: '"d" not in iay_fields[type]'

- name: 'Add {{ type }}.{{ key }} to imports list.'
  set_fact:
    iay_imports: '{{ iay_imports|union([inew]) }}'
  vars:
    inew:
      id: '{{ id }}'
      key: '{{ key }}'
      type: '{{ type }}'
      value: '{{ value }}'
