---

- block:
    - include_tasks: 'data_items.yml'
      loop: '{{ s3.data|dict2items }}'
      loop_control:
        loop_var: 'datas'
      vars:
        data_items: '{{ datas.value }}'
        type: '{{ provider }}_{{ datas.key }}'

    - include_tasks: 'resource_list.yml'
      loop: '{{ s3.resource }}'
      loop_control:
        loop_var: 'resource_list'
    
    - include_tasks: 'terraform.yml'


    - include_tasks: 'erase_data_items.yml'
      loop: '{{ s3.data|dict2items }}'
      loop_control:
        loop_var: 'datas'
      vars:
        data_items: '{{ datas.value.keys() }}'
        type: '{{ provider }}_{{ datas.key }}'

    - include_tasks: 'erase_resource_list.yml'
      loop: '{{ s3.resource|default([]) }}'
      loop_control:
        loop_var: 'resource_list'
        

  vars:
    s3:
      data:
        iam_policy_document:
          backend: '{{ aws_iam_policies_kms }}'
      resource:
        - kms_alias:
            backend:
              name: 'alias/{{ backend.head }}'
              target_key_id: '${aws_kms_key.backend.key_id}'
        - kms_key:
            backend:
              description: 'Encryption key for {{ backend.full }}'
              id: '${aws_kms_alias.backend.target_key_id}'
              policy: '${data.aws_iam_policy_document.backend.json}'
        - dynamodb_table:
            backend:
              attribute:
                name: 'LockID'
                type: 'S'
              hash_key: 'LockID'
              name: '{{ backend.head }}'
              read_capacity: 20
              write_capacity: 20
          s3_bucket:
            backend:
              acl: 'private'
              bucket: '{{ backend.head }}'
              encrypt: true
              force_destroy: false
              lifecycle_rule:
                abort_incomplete_multipart_upload_days: 1
                enabled: true
              noncurrent_version_expiration:
                days: '{{ infrastructure_backend_expire }}'
              server_side_encryption_configuration:
                rule:
                  apply_server_side_encryption_by_default:
                    kms_master_key_id: '${aws_kms_key.backend.arn}'
                    sse_algorithm: 'aws:kms'
              versioning:
                enabled: true

- include_tasks: 'write_terraform.yml'
  vars:
    file: '{{ provider }}_s3_backend'
    terraform:
      terraform:
        backend:
          s3:
            bucket: '{{ backend.head }}'
            dynamodb_table: '{{ backend.head }}'
            key: '{{ backend.tail }}'
            region: '{{ providers.value.region|default(aws_region) }}'
    
- include_tasks: 'terraform.yml'
