---

- name: 'Load terraform plugins.'
  args:
    chdir: '{{ path }}'
  shell: 'terraform init'

- include_tasks: 'terraform_import.yml'
  loop: '{{ imports }}'
  loop_control:
    loop_var: 'iargs'
  vars:
    n: '{{ iargs.type }}.{{ iargs.key }}'
    o: '{{ iargs.type }}_{{ iargs.key }}'

- name: 'Reset imports list.'
  set_fact:
    imports: []

- name: 'terraform {{ terraform_verb[state] }}'
  terraform:
    project_path: '{{ path }}'
    state: '{{ state }}'
