---

- name: 'Load terraform plugins.'
  args:
    chdir: '{{ path }}'
  shell: 'terraform init'

- name: 'Import existing resources.'
  include_tasks: 'terraform_import.yml'
  loop: '{{ imports }}'
  loop_control:
    loop_var: 'iargs'

- name: 'Reset imports list.'
  set_fact:
    imports: []

- name: 'terraform {{ terraform_verb[state] }}'
  terraform:
    project_path: '{{ path }}'
    state: '{{ state }}'
  register: 'terraform'

- debug:
    var: 'terraform.stdout_lines'
