---

- shell: '( set -x ; terraform init ) &> terraform.log'
  args:
    chdir: '{{ path }}'
  

- include_tasks: 'terraform_import.yml'
  loop: '{{ imports }}'
  loop_control:
    loop_var: 'iargs'
  vars:
    n: '{{ iargs.type }}.{{ iargs.key }}'
    o: '{{ iargs.type }}_{{ iargs.key }}'

- set_fact:
    imports: []

- shell: '( set -x ; terraform {{ action }} -auto-approve=true
            -input=false -lock=true -no-color ) 2>&1 | tee -a terraform.log'
  args:
    chdir: '{{ path }}'
  async: '{{ iay_async_timeout }}'
  poll: '{{ iay_async_poll }}'
