---

- shell: '( set -x ; terraform init -no-color ) >> terraform.log 2>&1'
  args:
    chdir: '{{ path }}'

- include_tasks: 'terraform_import.yml'
  loop: '{{ iay_imports }}'
  loop_control:
    loop_var: 'iargs'
  vars:
    n: '{{ iargs.type }}.{{ iargs.key }}'
    o: '{{ iargs.type }}_{{ iargs.key }}'

- set_fact:
    iay_imports: []

- shell: '( set -x ; terraform {{ action }} -auto-approve=true
            -input=false -lock=true -no-color ) >> terraform.log 2>&1'
  args:
    chdir: '{{ path }}'
  async: '{{ iay_async_timeout }}'
  poll: '{{ iay_async_poll }}'
