---


- name: 'Create output file.'
  copy:
    content: '{{ yaml|to_nice_json }}'
    dest: '{{ path }}/import.tf.json'
  vars:
    yaml:
      output:
        import_id:
          value: '{{ id }}'

- name: 'Refresh terraform to capture output.'
  shell: 'terraform refresh -no-color'
  args:
    chdir: '{{ path }}'
  ignore_errors: true
  register: 'refresh'

- name: 'Import resource if valid output was captured.'
  include_tasks: 'terraform_import_resource.yml'
  loop: '{{ refresh.stdout_lines
            |map("regex_search","^import_id = .*")
            |reject("none")
            |map("regex_replace","^import_id = ","")
            |list }}'
  loop_control:
    loop_var: 'ivalue'
  vars:
    iresource: '{{ iargs|combine({ "value" : ivalue }) }}'

- name: 'Remove output file.'
  file:
    path: '{{ path }}/import.tf.json'
    state: 'absent'
