---

- shell: '( set -x ; terraform init ) &> terraform.log'
  args:
    chdir: '{{ path }}'
  

- include_tasks: 'terraform_import.yml'
  loop: '{{ imports }}'
  loop_control:
    loop_var: 'iargs'
  vars:
    n: '{{ iargs.type }}.{{ iargs.key }}'
    o: '{{ iargs.type }}_{{ iargs.key }}'

- set_fact:
    imports: []

- name: '( set -x ; terraform {{ terraform_verb[state] }} ) >> terraform.log 2>&1'
  terraform:
    project_path: '{{ path }}'
    state: '{{ state }}'
  async: '{{ iay_async_timeout }}'
  poll: '{{ iay_async_poll }}'
