---

- name: 'Create data file.'
  include_tasks: 'data_write.yml'
  vars:
    key:   '{{ iargs.key   }}'
    type:  '{{ iargs.type  }}'
    value: '{{ iargs.value|combine({"depends_on":[]}) }}'

- include_tasks: 'terraform_import_scalar.yml'

- name: 'Remove data file.'
  file:
    path: '{{ path }}/data.{{ iargs.type }}.{{ iargs.key }}.tf.json'
    state: 'absent'
    
