---

- shell: 'tail -n +{{ iay_watch_l }} {{ iay_watch_f }}'
  register: 'iay_watch'

- block:

    - set_fact:
        iay_watch_l: '{{ iay_watch_l|int
                       + iay_watch.stdout_lines
                       |default([])|length }}'

    - debug:
        var: 'iay_watch.stdout_lines'

  when: 'iay_watch.stdout_lines|default([])|length > 0'

- async_status:
    jid: '{{ job.ansible_job_id }}'
  register: 'iay_watch'
  vars:
    job: '{{ lookup("vars", iay_watch_j) }}'
  when: 'job.ansible_job_id is defined'
