---


- set_fact:
    resource: {}

- set_fact:
    resource: '{{ resource|combine({ item : value[item] }) }}'
  loop: '{{ infrastructure_fields[type].r }}'
  when: 'item in value'

- include_tasks: 'write_terraform.yml'
  vars:
    file: '{{ type }}_r_{{ key }}'
    terraform:
      resource: '{{ { type : { key : resource } } }}'
  
- set_fact:
    imports: '{{ imports|union([ type + "." + key + " " + id]) }}'
  vars:
    id: "'{{ value[infrastructure_fields[type].i] }}'"
  when: 'infrastructure_fields[type].i in value'
