---

- include_tasks: 'write_terraform.yml'
  vars:
    file:
    terraform:
      data:
        resource:
          aws_iam_server_certificate:
      
    r_id: 'name'
    r_type: 'aws_iam_server_certificate'
